from __future__ import annotations

# (slug, name, category)
INTERESTS: list[tuple[str, str, str]] = [
    ("photography", "Фотография", "art"),
    ("cinema", "Кино", "art"),
    ("theatre", "Театр", "art"),
    ("painting", "Живопись", "art"),
    ("music_live", "Живая музыка", "music"),
    ("guitar", "Гитара", "music"),
    ("electronic_music", "Электронная музыка", "music"),
    ("running", "Бег", "sport"),
    ("gym", "Тренажёрный зал", "sport"),
    ("yoga", "Йога", "sport"),
    ("cycling", "Велосипед", "sport"),
    ("swimming", "Плавание", "sport"),
    ("hiking", "Походы", "nature"),
    ("camping", "Кемпинг", "nature"),
    ("gardening", "Садоводство", "nature"),
    ("travel", "Путешествия", "travel"),
    ("road_trips", "Автопутешествия", "travel"),
    ("city_walks", "Прогулки по городу", "travel"),
    ("cooking", "Кулинария", "food"),
    ("coffee", "Кофе", "food"),
    ("wine_tasting", "Дегустации", "food"),
    ("programming", "Программирование", "tech"),
    ("ai_ml", "ИИ и ML", "tech"),
    ("gaming", "Видеоигры", "games"),
    ("board_games", "Настольные игры", "games"),
    ("reading", "Чтение", "learning"),
    ("languages", "Иностранные языки", "learning"),
    ("science", "Наука", "learning"),
    ("volunteering", "Волонтёрство", "social"),
    ("parties", "Вечеринки", "social"),
    ("networking", "Нетворкинг", "social"),
    ("dogs", "Собаки", "nature"),
    ("cats", "Кошки", "nature"),
    ("fashion", "Мода", "art"),
    ("design", "Дизайн", "art"),
    ("startups", "Стартапы", "tech"),
    ("meditation", "Медитация", "sport"),
    ("dancing", "Танцы", "sport"),
    ("football", "Футбол", "sport"),
    ("skiing", "Лыжи/сноуборд", "sport"),
]
