"""initial schema

Revision ID: 03f0ea587029
Revises: 
Create Date: 2026-10-01 22:01:34.237153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '03f0ea587029'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('interests', postgresql.ARRAY(sa.String(length=80)), nullable=False),
    sa.Column('cities', postgresql.ARRAY(sa.String(length=120)), nullable=False),
    sa.Column('energy', sa.Float(), nullable=False),
    sa.Column('social', sa.Float(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activities_category'), 'activities', ['category'], unique=False)
    op.create_index(op.f('ix_activities_slug'), 'activities', ['slug'], unique=True)
    op.create_table('interests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interests_category'), 'interests', ['category'], unique=False)
    op.create_index(op.f('ix_interests_slug'), 'interests', ['slug'], unique=True)
    op.create_table('test_questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('trait', sa.String(length=60), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_question_category_position', 'test_questions', ['category', 'position'], unique=False)
    op.create_index(op.f('ix_test_questions_category'), 'test_questions', ['category'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('activity_preferences',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'activity_id', name='uq_activity_pref')
    )
    op.create_index(op.f('ix_activity_preferences_activity_id'), 'activity_preferences', ['activity_id'], unique=False)
    op.create_index(op.f('ix_activity_preferences_user_id'), 'activity_preferences', ['user_id'], unique=False)
    op.create_table('blocks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('blocker_id', sa.Uuid(), nullable=False),
    sa.Column('blocked_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('blocker_id <> blocked_id', name='ck_block_not_self'),
    sa.ForeignKeyConstraint(['blocked_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['blocker_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('blocker_id', 'blocked_id', name='uq_block_pair')
    )
    op.create_index(op.f('ix_blocks_blocked_id'), 'blocks', ['blocked_id'], unique=False)
    op.create_index(op.f('ix_blocks_blocker_id'), 'blocks', ['blocker_id'], unique=False)
    op.create_table('compatibility_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('vector', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compatibility_profiles_user_id'), 'compatibility_profiles', ['user_id'], unique=True)
    op.create_table('likes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('from_user_id', sa.Uuid(), nullable=False),
    sa.Column('to_user_id', sa.Uuid(), nullable=False),
    sa.Column('compatibility_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('from_user_id <> to_user_id', name='ck_like_not_self'),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_user_id', 'to_user_id', name='uq_like_pair')
    )
    op.create_index(op.f('ix_likes_from_user_id'), 'likes', ['from_user_id'], unique=False)
    op.create_index(op.f('ix_likes_to_user_id'), 'likes', ['to_user_id'], unique=False)
    op.create_table('matches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_a_id', sa.Uuid(), nullable=False),
    sa.Column('user_b_id', sa.Uuid(), nullable=False),
    sa.Column('compatibility_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('user_a_id <> user_b_id', name='ck_match_not_self'),
    sa.ForeignKeyConstraint(['user_a_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_b_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_a_id', 'user_b_id', name='uq_match_pair')
    )
    op.create_index('ix_match_users', 'matches', ['user_a_id', 'user_b_id'], unique=False)
    op.create_index(op.f('ix_matches_user_a_id'), 'matches', ['user_a_id'], unique=False)
    op.create_index(op.f('ix_matches_user_b_id'), 'matches', ['user_b_id'], unique=False)
    op.create_table('passes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('from_user_id', sa.Uuid(), nullable=False),
    sa.Column('to_user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('from_user_id <> to_user_id', name='ck_pass_not_self'),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_user_id', 'to_user_id', name='uq_pass_pair')
    )
    op.create_index(op.f('ix_passes_from_user_id'), 'passes', ['from_user_id'], unique=False)
    op.create_index(op.f('ix_passes_to_user_id'), 'passes', ['to_user_id'], unique=False)
    op.create_table('photos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photos_user_id'), 'photos', ['user_id'], unique=False)
    op.create_table('profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('about', sa.Text(), nullable=True),
    sa.Column('dating_goal', sa.String(length=30), nullable=False),
    sa.Column('age_min', sa.Integer(), nullable=False),
    sa.Column('age_max', sa.Integer(), nullable=False),
    sa.Column('gender_preference', postgresql.ARRAY(sa.String(length=20)), nullable=False),
    sa.Column('city_preference', sa.String(length=120), nullable=True),
    sa.Column('lifestyle', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profiles_city'), 'profiles', ['city'], unique=False)
    op.create_index('ix_profiles_city_goal', 'profiles', ['city', 'dating_goal'], unique=False)
    op.create_index(op.f('ix_profiles_dating_goal'), 'profiles', ['dating_goal'], unique=False)
    op.create_index(op.f('ix_profiles_user_id'), 'profiles', ['user_id'], unique=True)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_index('ix_refresh_user_revoked', 'refresh_tokens', ['user_id', 'revoked'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('reporter_id', sa.Uuid(), nullable=False),
    sa.Column('reported_id', sa.Uuid(), nullable=False),
    sa.Column('reason', sa.String(length=80), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('reporter_id <> reported_id', name='ck_report_not_self'),
    sa.ForeignKeyConstraint(['reported_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reporter_id', 'reported_id', 'reason', name='uq_report')
    )
    op.create_index(op.f('ix_reports_reported_id'), 'reports', ['reported_id'], unique=False)
    op.create_index(op.f('ix_reports_reporter_id'), 'reports', ['reporter_id'], unique=False)
    op.create_index(op.f('ix_reports_status'), 'reports', ['status'], unique=False)
    op.create_table('test_options',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['test_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_options_question_id'), 'test_options', ['question_id'], unique=False)
    op.create_table('test_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'category', name='uq_user_category_result')
    )
    op.create_index(op.f('ix_test_results_user_id'), 'test_results', ['user_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('match_id', sa.Uuid(), nullable=False),
    sa.Column('sender_id', sa.Uuid(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_message_match_created', 'messages', ['match_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_messages_match_id'), 'messages', ['match_id'], unique=False)
    op.create_index(op.f('ix_messages_sender_id'), 'messages', ['sender_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('match_id', sa.Uuid(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('explanation', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'activity_id', name='uq_match_activity_rec')
    )
    op.create_index('ix_rec_match_position', 'recommendations', ['match_id', 'position'], unique=False)
    op.create_index(op.f('ix_recommendations_match_id'), 'recommendations', ['match_id'], unique=False)
    op.create_table('test_answers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('option_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['option_id'], ['test_options.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['test_questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'question_id', name='uq_user_question_answer')
    )
    op.create_index('ix_answer_user_question', 'test_answers', ['user_id', 'question_id'], unique=False)
    op.create_index(op.f('ix_test_answers_user_id'), 'test_answers', ['user_id'], unique=False)
    op.create_table('user_interests',
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('interest_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['interest_id'], ['interests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id', 'interest_id'),
    sa.UniqueConstraint('profile_id', 'interest_id', name='uq_user_interest')
    )
    op.create_index('ix_user_interests_interest', 'user_interests', ['interest_id'], unique=False)
    op.create_table('message_reads',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('reader_id', sa.Uuid(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reader_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'reader_id', name='uq_message_read')
    )
    op.create_index(op.f('ix_message_reads_message_id'), 'message_reads', ['message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_reads_message_id'), table_name='message_reads')
    op.drop_table('message_reads')
    op.drop_index('ix_user_interests_interest', table_name='user_interests')
    op.drop_table('user_interests')
    op.drop_index(op.f('ix_test_answers_user_id'), table_name='test_answers')
    op.drop_index('ix_answer_user_question', table_name='test_answers')
    op.drop_table('test_answers')
    op.drop_index(op.f('ix_recommendations_match_id'), table_name='recommendations')
    op.drop_index('ix_rec_match_position', table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_messages_sender_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_match_id'), table_name='messages')
    op.drop_index('ix_message_match_created', table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_test_results_user_id'), table_name='test_results')
    op.drop_table('test_results')
    op.drop_index(op.f('ix_test_options_question_id'), table_name='test_options')
    op.drop_table('test_options')
    op.drop_index(op.f('ix_reports_status'), table_name='reports')
    op.drop_index(op.f('ix_reports_reporter_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_reported_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index('ix_refresh_user_revoked', table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_profiles_user_id'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_dating_goal'), table_name='profiles')
    op.drop_index('ix_profiles_city_goal', table_name='profiles')
    op.drop_index(op.f('ix_profiles_city'), table_name='profiles')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_photos_user_id'), table_name='photos')
    op.drop_table('photos')
    op.drop_index(op.f('ix_passes_to_user_id'), table_name='passes')
    op.drop_index(op.f('ix_passes_from_user_id'), table_name='passes')
    op.drop_table('passes')
    op.drop_index(op.f('ix_matches_user_b_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_user_a_id'), table_name='matches')
    op.drop_index('ix_match_users', table_name='matches')
    op.drop_table('matches')
    op.drop_index(op.f('ix_likes_to_user_id'), table_name='likes')
    op.drop_index(op.f('ix_likes_from_user_id'), table_name='likes')
    op.drop_table('likes')
    op.drop_index(op.f('ix_compatibility_profiles_user_id'), table_name='compatibility_profiles')
    op.drop_table('compatibility_profiles')
    op.drop_index(op.f('ix_blocks_blocker_id'), table_name='blocks')
    op.drop_index(op.f('ix_blocks_blocked_id'), table_name='blocks')
    op.drop_table('blocks')
    op.drop_index(op.f('ix_activity_preferences_user_id'), table_name='activity_preferences')
    op.drop_index(op.f('ix_activity_preferences_activity_id'), table_name='activity_preferences')
    op.drop_table('activity_preferences')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_test_questions_category'), table_name='test_questions')
    op.drop_index('ix_question_category_position', table_name='test_questions')
    op.drop_table('test_questions')
    op.drop_index(op.f('ix_interests_slug'), table_name='interests')
    op.drop_index(op.f('ix_interests_category'), table_name='interests')
    op.drop_table('interests')
    op.drop_index(op.f('ix_activities_slug'), table_name='activities')
    op.drop_index(op.f('ix_activities_category'), table_name='activities')
    op.drop_table('activities')
    # ### end Alembic commands ###
